// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

// Import and reexport all reducer arg types
import { InvokeScheduled } from "./invoke_scheduled_reducer.ts";
export { InvokeScheduled };
import { RequestAction } from "./request_action_reducer.ts";
export { RequestAction };
import { Spawn } from "./spawn_reducer.ts";
export { Spawn };

// Import and reexport all table handle types
import { PersonTableHandle } from "./person_table.ts";
export { PersonTableHandle };
import { ScheduledActionTableHandle } from "./scheduled_action_table.ts";
export { ScheduledActionTableHandle };
import { TileTableHandle } from "./tile_table.ts";
export { TileTableHandle };

// Import and reexport all types
import { ActionResult } from "./action_result_type.ts";
export { ActionResult };
import { ActionResultVariant } from "./action_result_variant_type.ts";
export { ActionResultVariant };
import { ActionType } from "./action_type_type.ts";
export { ActionType };
import { GameAction } from "./game_action_type.ts";
export { GameAction };
import { Person } from "./person_type.ts";
export { Person };
import { PutAction } from "./put_action_type.ts";
export { PutAction };
import { ScheduledAction } from "./scheduled_action_type.ts";
export { ScheduledAction };
import { Tile } from "./tile_type.ts";
export { Tile };

const REMOTE_MODULE = {
  tables: {
    person: {
      tableName: "person",
      rowType: Person.getTypeScriptAlgebraicType(),
      primaryKey: "conn",
      primaryKeyInfo: {
        colName: "conn",
        colType: Person.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    scheduled_action: {
      tableName: "scheduled_action",
      rowType: ScheduledAction.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: ScheduledAction.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    tile: {
      tableName: "tile",
      rowType: Tile.getTypeScriptAlgebraicType(),
      primaryKey: "pos",
      primaryKeyInfo: {
        colName: "pos",
        colType: Tile.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    invoke_scheduled: {
      reducerName: "invoke_scheduled",
      argsType: InvokeScheduled.getTypeScriptAlgebraicType(),
    },
    request_action: {
      reducerName: "request_action",
      argsType: RequestAction.getTypeScriptAlgebraicType(),
    },
    spawn: {
      reducerName: "spawn",
      argsType: Spawn.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.2.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "InvokeScheduled", args: InvokeScheduled }
| { name: "RequestAction", args: RequestAction }
| { name: "Spawn", args: Spawn }
;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  invokeScheduled(args: ScheduledAction) {
    const __args = { args };
    let __writer = new BinaryWriter(1024);
    InvokeScheduled.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("invoke_scheduled", __argsBuffer, this.setCallReducerFlags.invokeScheduledFlags);
  }

  onInvokeScheduled(callback: (ctx: ReducerEventContext, args: ScheduledAction) => void) {
    this.connection.onReducer("invoke_scheduled", callback);
  }

  removeOnInvokeScheduled(callback: (ctx: ReducerEventContext, args: ScheduledAction) => void) {
    this.connection.offReducer("invoke_scheduled", callback);
  }

  requestAction(action: GameAction) {
    const __args = { action };
    let __writer = new BinaryWriter(1024);
    RequestAction.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("request_action", __argsBuffer, this.setCallReducerFlags.requestActionFlags);
  }

  onRequestAction(callback: (ctx: ReducerEventContext, action: GameAction) => void) {
    this.connection.onReducer("request_action", callback);
  }

  removeOnRequestAction(callback: (ctx: ReducerEventContext, action: GameAction) => void) {
    this.connection.offReducer("request_action", callback);
  }

  spawn() {
    this.connection.callReducer("spawn", new Uint8Array(0), this.setCallReducerFlags.spawnFlags);
  }

  onSpawn(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("spawn", callback);
  }

  removeOnSpawn(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("spawn", callback);
  }

}

export class SetReducerFlags {
  invokeScheduledFlags: CallReducerFlags = 'FullUpdate';
  invokeScheduled(flags: CallReducerFlags) {
    this.invokeScheduledFlags = flags;
  }

  requestActionFlags: CallReducerFlags = 'FullUpdate';
  requestAction(flags: CallReducerFlags) {
    this.requestActionFlags = flags;
  }

  spawnFlags: CallReducerFlags = 'FullUpdate';
  spawn(flags: CallReducerFlags) {
    this.spawnFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get person(): PersonTableHandle {
    return new PersonTableHandle(this.connection.clientCache.getOrCreateTable<Person>(REMOTE_MODULE.tables.person));
  }

  get scheduledAction(): ScheduledActionTableHandle {
    return new ScheduledActionTableHandle(this.connection.clientCache.getOrCreateTable<ScheduledAction>(REMOTE_MODULE.tables.scheduled_action));
  }

  get tile(): TileTableHandle {
    return new TileTableHandle(this.connection.clientCache.getOrCreateTable<Tile>(REMOTE_MODULE.tables.tile));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
